language: node_js
node_js:
- '0.10'
before_script:
- npm install
script:
- npm test
notifications:
  hipchat:
    rooms:
      secure: KQjI8rc5oUA75kU+UsNcW1Vfp+x26xE0yT9910epoR9FiaqTzTj10OYPdsLCgfuN2VJCE/lSici585FunRo9M5OaWUgGb1CbHBKt4b/ZseY3tcPQcHyaNgJwbFdhZs7ri7NzrHrKkGzUzDwzWQMa2dttAxAhbFwH2nZqFrZeHt4=
