language: node_js
node_js:
- '0.10'
before_script:
- npm install
script:
- npm test
notifications:
  slack:
    secure: mSuQG1/B+T36dWXlKAr9QLnCIdOybp8QvzB1HBSINAslYGvdGm+rlfT/JxjPN3ZcvKhU52Efmq1df7BjG/1HVnwx096OU8wphJodPRAdIHxP3C8t/7r3nj92GNKW6zTNTj1Z7oP4b3TkTMEzAXJLZxUWKdCyoXIaVWATBHxcnlw=
